### ISSUE TITLE
maven "project building request missing"

### ISSUE THREAD

**Issue by Drewster727** [CycloneDX/cyclonedx-maven-plugin#11]
Hi--
In my java project, I have cyclonedx setup in the pom.xml per below:
```
           <plugin>
                <groupId>org.cyclonedx</groupId>
                <artifactId>cyclonedx-maven-plugin</artifactId>
                <executions>
                  <execution>
                    <phase>package</phase>
                    <goals>
                      <goal>makeAggregateBom</goal>
                    </goals>
                  </execution>
                </executions>
                <configuration>
                  <includeCompileScope>true</includeCompileScope>
                  <includeProvidedScope>true</includeProvidedScope>
                  <includeRuntimeScope>true</includeRuntimeScope>
                  <includeSystemScope>true</includeSystemScope>
                  <includeTestScope>false</includeTestScope>
                </configuration>
            </plugin>
```

I'm seeing the following error when mvn package runs:
```
[ERROR] Failed to execute goal org.cyclonedx:cyclonedx-maven-plugin:1.3.1:makeAggregateBom (default) on project data-warehouse-parent: Execution default of goal org.cyclonedx:cyclonedx-maven-plugin:1.3.1:makeAggregateBom failed: project building request missing -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.cyclonedx:cyclonedx-maven-plugin:1.3.1:makeAggregateBom (default) on project data-warehouse-parent: Execution default of goal org.cyclonedx:cyclonedx-maven-plugin:1.3.1:makeAggregateBom failed: project building request missing
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.cyclonedx:cyclonedx-maven-plugin:1.3.1:makeAggregateBom failed: project building request missing
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:115)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.IllegalStateException: project building request missing
	at org.apache.maven.project.MavenProject.checkProjectBuildingRequest(MavenProject.java:2231)
	at org.apache.maven.project.MavenProject.getParent(MavenProject.java:371)
	at org.cyclonedx.maven.BaseCycloneDxMojo.getClosestMetadata(BaseCycloneDxMojo.java:250)
	at org.cyclonedx.maven.BaseCycloneDxMojo.convert(BaseCycloneDxMojo.java:234)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.cyclonedx.maven.CycloneDxAggregateMojo.execute(CycloneDxAggregateMojo.java:47)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
	... 20 more
```

Interestingly... when I run this from my development machine (via IntelliJ) it works without issue, and the target folders/boms get generated.

Any tips on resolving this?

Build box details:
```
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 10:22:22-0500)
Maven home: C:\apache-maven-3.1.1
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_65\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows server 2012 r2", version: "6.3", arch: "amd64", family: "dos"
```

**Comment by stevespringett** [comment]
That's a new one...  No clue. Wouldn't even know how to begin to reproduce. That version of Maven is really outdated. Perhaps try a newer version and see what happens.

**Comment by stevespringett** [comment]
If the poms are defined in the parent as modules, the yes, aggregate will
produce a bom with all components. I think it also produces the individual
ones as well. Can’t remember

— Steve

From: Drew <notifications@github.com> <notifications@github.com>
Reply: CycloneDX/cyclonedx-maven-plugin
<reply@reply.github.com>
<reply@reply.github.com>
Date: January 24, 2019 at 7:26:53 AM
To: CycloneDX/cyclonedx-maven-plugin
<cyclonedx-maven-plugin@noreply.github.com>
<cyclonedx-maven-plugin@noreply.github.com>
CC: Steve Springett <steve@springett.us> <steve@springett.us>, Mention
<mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [CycloneDX/cyclonedx-maven-plugin] maven "project building
request missing" (#11)

@stevespringett <https://github.com/stevespringett> I updated to maven

**Comment by labrute** [comment]
What is the minimum version of maven supported ?

**Comment by stevespringett** [comment]
It requires maven 3.0 to run (as defined https://github.com/CycloneDX/cyclonedx-maven-plugin/blob/master/pom.xml#L122), but older versions of Maven do have issues which is outside of our control. I highly recommend using Maven 3.5 or higher. Everything else is 3 or more years out of date. 

If pom v5 ever becomes a thing, the project will likely be quick to adopt it as pom v4 has too many limitations compared to more modern ecosystems.
